import Resources from '../../resources';

export const ChineseCityList = [
    {key: '0', value: '其他', text: Resources.getInstance().cityQT},
    {key: '1', value: '北京', text: Resources.getInstance().cityBJ},
    {key: '2', value: '上海', text: Resources.getInstance().citySH},
    {key: '3', value: '广州', text: Resources.getInstance().cityGZ},
    {key: '4', value: '深圳', text: Resources.getInstance().citySZ},
    {key: '5', value: '天津', text: Resources.getInstance().cityTJ},
    {key: '6', value: '杭州', text: Resources.getInstance().cityHZ},
    {key: '7', value: '南京', text: Resources.getInstance().cityNJ},
    {key: '8', value: '济南', text: Resources.getInstance().cityJN},
    {key: '9', value: '重庆', text: Resources.getInstance().cityCQ},
    {key: '10', value: '青岛', text: Resources.getInstance().cityQD},
    {key: '11', value: '大连', text: Resources.getInstance().cityDL},
    {key: '12', value: '宁波', text: Resources.getInstance().cityNB},
    {key: '13', value: '厦门', text: Resources.getInstance().cityXM},
    {key: '14', value: '重庆', text: Resources.getInstance().cityCQ},
    {key: '15', value: '成都', text: Resources.getInstance().cityCD},
    {key: '16', value: '武汉', text: Resources.getInstance().cityWH},
    {key: '17', value: '哈尔滨', text: Resources.getInstance().cityHEB},
    {key: '18', value: '沈阳', text: Resources.getInstance().citySY},
    {key: '19', value: '西安', text: Resources.getInstance().cityXA},
    {key: '20', value: '长春', text: Resources.getInstance().cityCC},
    {key: '21', value: '长沙', text: Resources.getInstance().cityCS},
    {key: '22', value: '福州', text: Resources.getInstance().cityFZ},
    {key: '23', value: '郑州', text: Resources.getInstance().cityZZ},
    {key: '24', value: '石家庄', text: Resources.getInstance().citySJZ},
    {key: '25', value: '苏州', text: Resources.getInstance().citySZ1},
    {key: '26', value: '佛山', text: Resources.getInstance().cityFS},
    {key: '27', value: '东莞', text: Resources.getInstance().cityDG},
    {key: '28', value: '无锡', text: Resources.getInstance().cityWX},
    {key: '29', value: '烟台', text: Resources.getInstance().cityYT},
    {key: '30', value: '太原', text: Resources.getInstance().cityTY},
    {key: '31', value: '合肥', text: Resources.getInstance().cityHF},
    {key: '32', value: '南昌', text: Resources.getInstance().cityNC},
    {key: '33', value: '南宁', text: Resources.getInstance().cityNN},
    {key: '34', value: '昆明', text: Resources.getInstance().cityKM},
    {key: '35', value: '温州', text: Resources.getInstance().cityWZ},
    {key: '36', value: '淄博', text: Resources.getInstance().cityZB},
    {key: '37', value: '唐山', text: Resources.getInstance().cityTS},
];